#!/usr/bin/env bash
#
# Summary: Prints the name of current todo file
#
# Usage: todo file

if [ -f .todo ]; then
  echo .todo
  exit
fi

if [ -n "${TODO_FILE}" ]; then
  echo "${TODO_FILE}"
  exit
fi

echo .todo
