#!/usr/bin/env bash
#
# Summary: Complete a todo item by number
#
# Usage: todo do <number>

line=$1

todofile="$(todo-file)"
tmpfile="$(mktemp)"

sed "${line}d" "${todofile}" > "${tmpfile}" && mv "${tmpfile}" "${todofile}"
